/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BudgifyTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BudgifyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "EmailIdentity": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "ProcessRecurring": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}